import "./globals.css";

import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

const SessionProvider = dynamic(
  () => import("@/components/providers/SessionProvider")
);
const NotificationsProvider = dynamic(
  () => import("@/components/providers/NotificationsProvider")
);
const AuthProvider = dynamic(
  () => import("@/features/auth/components/providers/AuthProvider")
);
const ModalProvider = dynamic(
  () => import("@/components/providers/ModalProvider")
);

const font = Inter({
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-[#F4F1FF] ${font.className}`}>
        <SessionProvider>
          <AuthProvider>
            <NotificationsProvider>
              <ModalProvider>{children}</ModalProvider>
            </NotificationsProvider>
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
