import dynamic from "next/dynamic";
import Image from "next/image";

const Logo = dynamic(() => import("@/components/ui/Logo"));

export const metadata = {
  title: "Heyz - Authentication",
  description: "Generated by Hazim Tulumovic (heyz)",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-[100dvh] flex justify-between items-center">
      {/** Main */}
      <main className="basis-[50%] h-full p-20">
        <Logo className="mx-auto" />
        {children}
      </main>
      {/** Image  */}
      <Image
        src={"/images/auth-banner.webp"}
        loading="lazy"
        width={1200}
        height={1080}
        alt="Banner"
        className="basis-[50%] w-full h-full"
      />
    </div>
  );
}
