import { Inter } from "next/font/google";

const font = Inter({
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Heyz - Chatting App",
  description: "Generated by Hazim Tulumovic (heyz)",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-[100dvh] flex justify-between items-center">
      {/** Main */}
      <main className="bg-[red] basis-[50%] h-full">{children}</main>
      {/** Image  */}
      <div className="basis-[50%] bg-[yellow] h-full"></div>
    </div>
  );
}
